##################################################################################
# Tomcat Node Types
# Author: kemi
##################################################################################
tosca_definitions_version: cloudify_dsl_1_1

plugins:
  tomcat_plugin:
    executor: host_agent
    source: https://github.com/kemiz/tomcat-plugin-cfy3/archive/master.zip

node_types:

 ##################################################################################
 # Tomcat Server Type
 # A Tomcat server type that can be used to install and control a tomcat instance.
 # The implementation uses: "sudo service <service_name> start / stop / restart"
 # to control the service operation
 ##################################################################################

  cloudify.nodes.TomcatServer:
    derived_from: cloudify.nodes.ServiceInstaller
    properties:
      service_name:
        default: 'tomcat'
      version:
        default: 7
      server_config:
        default:
          server_xml: None
          web_xml: None
          webapps_dir: None
          catalina_home: None
          java_opts: None
      config:
        default:
          package_list:
            - 'openjdk-7-jdk'
            - 'tomcat7'
    interfaces:
      cloudify.interfaces.lifecycle:
        # Overriding the start impl in order to configure the service in advance
        start:
          implementation: tomcat_plugin.tomcat_plugin.tasks.start_tomcat
          inputs:
            service_name:
              default: { get_property: [ SELF, service_name ] }
            server_config:
              default: { get_property: [ SELF, server_config ]}
      tomcat.interfaces:
        configure:
          implementation: tomcat_plugin.tomcat_plugin.tasks.configure


  ##################################################################################
  # Tomcat Simple Application Type (WAR)
  ##################################################################################

  cloudify.nodes.TomcatApp:
    derived_from: cloudify.nodes.ApplicationModule
    properties:
      name:
        default: 'TomcatApp'
      artefact_url:
        default: None
      maven_app:
        default: False


relationships:
  app_deployed_in_tomcat:
    derived_from: cloudify.relationships.contained_in
    target_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        postconfigure:
          implementation: tomcat_plugin.tomcat_plugin.tasks.deploy_tomcat_app
          inputs:
            artefact_url:
              default: { get_property: [ SOURCE,  artefact_url ] }
            app_name:
              default: { get_property: [ SOURCE,  name ] }