##################################################################################
# Tomcat Node Types
# Author: kemi
##################################################################################
tosca_definitions_version: cloudify_dsl_1_1

plugins:
  tomcat_plugin:
    executor: host_agent
    source: https://github.com/kemiz/tomcat-plugin-cfy3/archive/master.zip

workflows:
    check_tomcat_health:
        mapping: tomcat_plugin.tomcat_plugin.workflows.check_tomcat_health

node_types:

 ##################################################################################
 # Tomcat Server Type
 # A Tomcat server type that can be used to install and control a tomcat instance.
 # The implementation uses: "sudo service <service_name> start / stop / restart"
 # to control the service operation
 ##################################################################################

  cloudify.nodes.TomcatServer:
    derived_from: cloudify.nodes.ServiceInstaller
    properties:
      service_name:
        default: 'tomcat7'
      version:
        default: 7
      server_config:
        default:
#          server_xml:
#          web_xml:
          tomcat_home_dir: '/etc/tomcat7/'
          webapps_dir: '/var/lib/tomcat7/webapps/'
          catalina_home: '/usr/share/tomcat7/'
          java_opts: '-server -Xmx512m'
      config:
        default:
          package_list:
            - 'openjdk-7-jdk'
            - 'tomcat7'
            - 'maven2'
            - 'unzip'
    interfaces:
      cloudify.interfaces.lifecycle:
        # Overriding the start impl in order to configure the service in advance
        configure:
          implementation: tomcat_plugin.tomcat_plugin.tasks.configure
          inputs:
            server_config:
              default: { get_property: [ SELF, server_config ] }
        start:
          implementation: tomcat_plugin.tomcat_plugin.tasks.start_tomcat
          inputs:
            service_name:
              default: { get_property: [ SELF, service_name ] }
      tomcat.commands:
        check_tomcat_health: tomcat_plugin.tomcat_plugin.tasks.check_tomcat_health

  ##################################################################################
  # Tomcat Simple Application Type (WAR)
  ##################################################################################

  cloudify.nodes.TomcatApp:
    derived_from: cloudify.nodes.ApplicationModule
    properties:
      name:
        default: 'TomcatApp'
      artefact_url:
        default: None
      maven_app:
        default: False
      branch:
        default: None

relationships:
  app_deployed_in_tomcat:
    derived_from: cloudify.relationships.contained_in
    target_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        postconfigure:
          implementation: tomcat_plugin.tomcat_plugin.tasks.deploy_tomcat_app
          inputs:
            artefact_url:
              default: { get_property: [ SOURCE, artefact_url ] }
            webapps_dir:
              default: { get_property: [ TARGET, server_config, webapps_dir ] }
            app_name:
              default: { get_property: [ SOURCE, name ] }
            maven_app:
              default: { get_property: [ SOURCE, maven_app ] }
            branch:
              default: { get_property: [ SOURCE, branch ] }