##################################################################################
# Tomcat Node Types
# Author: kemi
##################################################################################
tosca_definitions_version: cloudify_dsl_1_1

plugins:
  tomcat_plugin:
    executor: host_agent
    source: https://github.com/kemiz/tomcat-plugin-cfy3/archive/master.zip

node_types:

 ##################################################################################
 # Tomcat Server Type
 # A Tomcat server type that can be used to install and control a tomcat instance.
 # The implementation uses: "sudo service <service_name> start / stop / restart"
 # to control the service operation
 ##################################################################################

  cloudify.nodes.TomcatServer:
    derived_from: cloudify.nodes.ServiceInstaller
    properties:
      service_name:
        default: 'tomcat'
      version:
        default: 7
      server_config:
        default:
          server_xml:
          web_xml:
      java_config:
        default:
          xms:
          xmx:
      config:
        default:
          package_list:
            - 'openjdk-7-jdk'
            - 'tomcat7'
    interfaces:
      cloudify.interfaces.lifecycle:
        # Overriding the start impl in order to configure the service in advance
        start:
          implementation: tomcat_plugin.tomcat_plugin.tasks.start_tomcat
      tomcat.interfaces:
        configure:
          implementation: tomcat_plugin.tomcat_plugin.tasks.configure

  ##################################################################################
  # Tomcat Application Type
  # TODO: Implementation
  ##################################################################################

  cloudify.nodes.TomcatApplication:
    derived_from: cloudify.nodes.application.MavenApp
    properties:
      name:
        default: 'my_tomcat_app'
      artefact_url:
        default: 'https://s3-eu-west-1.amazonaws.com/kemiz/MongoDBWebapp.zip'
        description: >
          Application file to deploy
      war_file:
        default: None
      build_on_deploy:
        default: True
        type: boolean

  cloudify.nodes.application.MavenApp:
    derived_from: cloudify.nodes.ServiceInstaller
    properties:
      name:
        default: 'my_maven_app'
      version:
        default: '1.0'
      config:
        default:
          package_list:
            - 'openjdk-7-jdk'
            - 'maven2'
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: maven_plugin.maven_plugin.tasks.package


relationships:
  app_deployed_in_tomcat:
    derived_from: cloudify.relationships.contained_in
    target_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        postconfigure:
          implementation: tomcat_plugin.tomcat_plugin.tasks.deploy_tomcat_app
          inputs:
            war_file_url:
              default: { get_property: [ SOURCE,  war_file_url ] }
            app_name:
              default: { get_property: [ SOURCE,  name ] }